-- DATABASE ATIVO

CREATE TABLE tbl_ativo
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TICKER VARCHAR(10) NOT NULL,
    ISIN VARCHAR(12) NOT NULL,
    NM_EMPERSA VARCHAR(200) NOT NULL,
    DT_HR_ATUALIZACAO_UTC DATETIME NOT NULL
);

CREATE TABLE tbl_categoria
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NM_CATEGORIA VARCHAR(50) NOT NULL,
    DT_HR_ATUALIZACAO_UTC DATETIME NOT NULL
);


-- DATABASE EMPRESA
CREATE DATABASE EMPRESA;

CREATE TABLE tbl_empresa
(
    ID INT IDENTITY(1,1) PRIMARY KEY,

    ID_SEGMENTO INT NOT NULL,
    ID_MERCADO INT NOT NULL,

    COD_CVM INT NOT NULL,
    SIGLA VARCHAR(4) NOT NULL,
    RAZAO_SOCIAL VARCHAR(300) NOT NULL,
    NOME_FANTASIA VARCHAR(300) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    MKT_INDICATOR INT NOT NULL,
    TYPE_BDR INT NOT NULL,
    DT_LISTAGEM DATE NOT NULL,
    STATUS VARCHAR(5) NOT NULL,
    TIPO INT NOT NULL,

    DT_HR_ATUALIZACAO_UTC DATETIME NOT NULL
);

CREATE TABLE tbl_mercado
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    SIGLA_MERCADO VARCHAR(20) NOT NULL,
    NM_MERCADO VARCHAR(100) NOT NULL,
    DT_HR_ATUALIZACAO_UTC DATETIME NOT NULL
);

CREATE TABLE tbl_segmento
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NM_SEGMENTO VARCHAR(50) NOT NULL,
    DT_HR_ATUALIZACAO_UTC DATETIME NOT NULL
);

