-- DATABASE ATIVO
CREATE TABLE tbl_ativos_listados_b3(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TICKER VARCHAR(10) NOT NULL,
    ISIN VARCHAR(12) NOT NULL,
    DESCRICAO_BMF VARCHAR(200) NOT NULL,
    ID_EMPRESA INT NOT NULL,
    DT_HR_ATUALIZACAO_UTC DATETIME NOT NULL,
);


CREATE TABLE tbl_cotacao_listados_b3(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_ATIVO INT NOT NULL,
    DT_COTACAO DATE NOT NULL,
    VL_ABERTURA DECIMAL(10,2) NOT NULL,
    VL_FECHAMENTO DECIMAL(10,2) NOT NULL,
    VL_FECHAMENTO_AJUSTADO DECIMAL(10,2) NOT NULL,
    VL_MINIMO DECIMAL(10,2) NOT NULL,
    VL_MAXIMO DECIMAL(10,2) NOT NULL,
    VL_MEDIO DECIMAL(10,2) NOT NULL,
    VL_VOLUME_NEGOCIADO DECIMAL(10,2) NOT NULL,

    DT_HR_ATUALIZACAO_UTC DATETIME NOT NULL

    CONSTRAINT FK_cotacao_ativo FOREIGN KEY (ID_ATIVO) REFERENCES tbl_ativos_listados_b3(ID)
);


-- CREATE TABLE tbl_categoria
-- (
--     ID INT IDENTITY(1,1) PRIMARY KEY,
--     NM_CATEGORIA VARCHAR(50) NOT NULL,
--     DT_HR_ATUALIZACAO_UTC DATETIME NOT NULL
-- );


-- DATABASE EMPRESA
CREATE DATABASE EMPRESA;

CREATE TABLE tbl_empresa
(
    ID INT IDENTITY(1,1) PRIMARY KEY,

    ID_SEGMENTO INT NOT NULL,
    ID_MERCADO INT NOT NULL,
    ID_TYPE_BDR INT NOT NULL,

    COD_CVM INT NOT NULL,
    SIGLA VARCHAR(4) NOT NULL,
    RAZAO_SOCIAL VARCHAR(300) NOT NULL,
    NOME_FANTASIA VARCHAR(300) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    MKT_INDICATOR INT NOT NULL,
    DT_LISTAGEM DATE NOT NULL,
    STATUS VARCHAR(5) NOT NULL,
    TIPO INT NOT NULL,

    DT_HR_ATUALIZACAO_UTC DATETIME NOT NULL

    CONSTRAINT FK_empresa_segmento FOREIGN KEY (ID_SEGMENTO) REFERENCES tbl_segmento(ID),
    CONSTRAINT FK_empresa_mercado FOREIGN KEY (ID_MERCADO) REFERENCES tbl_mercado(ID),
    CONSTRAINT FK_empresa_type_bdr FOREIGN KEY (ID_TYPE_BDR) REFERENCES tbl_mercado(ID)
);

CREATE TABLE tbl_mercado
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    SIGLA_MERCADO VARCHAR(20) NOT NULL,
    NM_MERCADO VARCHAR(100) NOT NULL,
    DT_HR_ATUALIZACAO_UTC DATETIME NOT NULL
);

CREATE TABLE tbl_setor
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NM_SETOR VARCHAR(50) NOT NULL,
    DT_HR_ATUALIZACAO_UTC DATETIME NOT NULL
);

CREATE TABLE tbl_subsetor
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_SETOR INT NOT NULL,
    NM_SUBSETOR VARCHAR(50) NOT NULL,
    DT_HR_ATUALIZACAO_UTC DATETIME NOT NULL

    CONSTRAINT FK_subsetor_setor FOREIGN KEY (ID_SETOR) REFERENCES tbl_setor(ID)
);

CREATE TABLE tbl_segmento
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_SUBSETOR INT NOT NULL,

    NM_SEGMENTO VARCHAR(50) NOT NULL,
    DT_HR_ATUALIZACAO_UTC DATETIME NOT NULL

    CONSTRAINT FK_segmento_subsetor FOREIGN KEY (ID_SUBSETOR) REFERENCES tbl_subsetor(ID)
);

