-- DATABASE ATIVO

CREATE TABLE tbl_ativo
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TICKER VARCHAR(10) NOT NULL,
    ISIN VARCHAR(12) NOT NULL,
    NM_EMPERSA VARCHAR(200) NOT NULL,
    DT_HR_ATUALIZACAO_UTC DATETIME NOT NULL
);

CREATE TABLE tbl_categoria
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NM_CATEGORIA VARCHAR(50) NOT NULL,
    DT_HR_ATUALIZACAO_UTC DATETIME NOT NULL
);
